// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbltyxypjvbavejkkcer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibHR5eHlwanZiYXZlamtrY2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTYyNjMsImV4cCI6MjA3NTE3MjI2M30.Zfp_n3S6Fdb3gFd4rr9s8PmCE8qRK8RnxQKPTpuhDbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});